version: 2.2.2

build:
  os: ubuntu-22.04
  tools:
    python: 3.12
    astropy: 6.1
    #h5py
    #matplotlib
    reproject: 0.13.1
    #scipy
    #specutils
    #tqdm

#python:
#  install:
#    -requirements:

sphinx:
  configuration: doc/src/conf.py