[build-system]
requires = [
    "setuptools",
    # "setuptools_scm>=6.2",
    "wheel",
]
build-backend = "setuptools.build_meta"

# [tool.setuptools_scm]
# write_to = "astropy/_version.py"

[constant]
board_size = 3

[project]
name = "rapyuta"
authors = [
    {name = "D. HU"},
    {email = "dangning.hu@outlook.com"}
]
maintainers = [
    {name = "D. HU"},
    {email = "dangning.hu@outlook.com"}
]
license = {text = "BSD 3-Clause License"}
description = "Regular AstroPY UTility Assemblage"
keywords = [
    "astronomy",
    "astrophysics",
    "astrometry",
    "imaging",
    "photometry",
    "spectroscopy",
    "space",
    "spitzer",
    "akari",
    "jwst",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Fortran",
    "Programming Language :: IDL",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
]
requires-python = ">=3.8"
dependencies = [
    'astropy>=5.1',
    'colorama',
    'h5py',
    'matplotlib', 
    'numpy',
    'photutils',
    'reproject>=0.7.1',
    'scipy',
    'specutils',
    'tqdm',
]
dynamic = ["version", "readme"]

[project.urls]
repository = "https://github.com/kxxdhdn/RAPYUTA"
# homepage = ""
# documentation = ""
manual = "https://github.com/kxxdhdn/RAPYUTA/man"
reports = "https://github.com/kxxdhdn/RAPYUTA/issues"
source = "https://github.com/kxxdhdn/RAPYUTA/rapyuta"

[project.scripts]
rapyboost = "rapyuta:boost_rapyuta"

[tool.setuptools]
zip-safe = false
include-package-data = true # (true by default)

[tool.setuptools.dynamic]
version = {attr = "rapyuta.version.__version__"}
readme = {file = "README.org"}

# [tool.setuptools.packages]
# find = {} # Scan the project directory with the default parameters

[tool.setuptools.packages.find]
where = ["."] # list of folders that contain the packages (["."] by default)
include = ["rapyuta*"] # package names should match these glob patterns (["*"] by default)
exclude = ["rapyuta._dev"] # exclude packages matching these glob patterns (empty by default)
namespaces = false # to disable scanning PEP 420 namespaces (true by default)

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.linux]
archs = ["auto", "aarch64"]